name: Build Arti + Transports (Windows x64 + i686)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # ежедневно 06:00 UTC

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      # ---------------- Checkout meta repo ----------------
      - name: Checkout meta repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      # ---------------- Install SQLite ----------------
      - name: Install SQLite (for static build)
        run: choco install sqlite -y

      # ---------------- Rust / arti ----------------
      - name: Setup Rust (MSVC x64 + i686)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-pc-windows-msvc
            i686-pc-windows-msvc

      - name: Clone Arti (mirror)
        run: |
          git clone --depth 1 --branch main https://github.com/${{ github.repository_owner }}/arti-mirror arti
          cd arti
          git fetch --tags --force

      - name: Detect Arti version
        id: arti_ver
        working-directory: arti
        run: |
          $ver = git tag --list "arti-*" --sort=-creatordate | Select-Object -First 1
          if ([string]::IsNullOrEmpty($ver)) { $ver="arti-v0.0.0" }
          echo "arti_version=$ver" | Out-File -Append -FilePath $env:GITHUB_ENV
          Write-Host "Arti version: $ver"

      - name: Build arti.exe (x64 & i686)
        working-directory: arti
        run: |
          cargo build --release --target x86_64-pc-windows-msvc --features static
          cargo build --release --target i686-pc-windows-msvc --features static
          New-Item -ItemType Directory -Force ..\dist | Out-Null
          Copy-Item target\x86_64-pc-windows-msvc\release\arti.exe ..\dist\arti-x64.exe
          Copy-Item target\i686-pc-windows-msvc\release\arti.exe   ..\dist\arti-i686.exe

      # ---------------- Go toolchain ----------------
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # ---------- lyrebird ----------
      - name: Clone lyrebird (Go)
        run: git clone --depth 1 https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird.git

      - name: Build lyrebird.exe (x64)
        working-directory: lyrebird/cmd/lyrebird
        run: go build -o ../../../dist/lyrebird-x64.exe .

      - name: Build lyrebird.exe (i686)
        working-directory: lyrebird/cmd/lyrebird
        run: |
          $env:GOOS="windows"
          $env:GOARCH="386"
          go build -o ../../../dist/lyrebird-i686.exe .

      # ---------- snowflake (client) ----------
      - name: Clone snowflake (Go)
        run: git clone --depth 1 https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake.git

      - name: Build snowflake-client.exe (x64)
        working-directory: snowflake/client
        run: go build -o ../../dist/snowflake-client-x64.exe .

      - name: Build snowflake-client.exe (i686)
        working-directory: snowflake/client
        run: |
          $env:GOOS="windows"
          $env:GOARCH="386"
          go build -o ../../dist/snowflake-client-i686.exe .

      # ---------- webtunnel (client) ----------
      - name: Clone webtunnel (Go)
        run: git clone --depth 1 https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel.git

      - name: Build webtunnel-client.exe (x64)
        working-directory: webtunnel/main/client
        run: go build -o ../../../dist/webtunnel-client-x64.exe .

      - name: Build webtunnel-client.exe (i686)
        working-directory: webtunnel/main/client
        run: |
          $env:GOOS="windows"
          $env:GOARCH="386"
          go build -o ../../../dist/webtunnel-client-i686.exe .

      # ---------------- упаковка ----------------
      - name: Create ZIPs
        run: |
          Compress-Archive -Path dist\arti-x64.exe             -DestinationPath dist\arti-x64.zip
          Compress-Archive -Path dist\arti-i686.exe            -DestinationPath dist\arti-i686.zip
          Compress-Archive -Path dist\lyrebird-x64.exe         -DestinationPath dist\lyrebird-x64.zip
          Compress-Archive -Path dist\lyrebird-i686.exe        -DestinationPath dist\lyrebird-i686.zip
          Compress-Archive -Path dist\snowflake-client-x64.exe -DestinationPath dist\snowflake-x64.zip
          Compress-Archive -Path dist\snowflake-client-i686.exe -DestinationPath dist\snowflake-i686.zip
          Compress-Archive -Path dist\webtunnel-client-x64.exe -DestinationPath dist\webtunnel-x64.zip
          Compress-Archive -Path dist\webtunnel-client-i686.exe -DestinationPath dist\webtunnel-i686.zip
          Compress-Archive -Path dist\*.exe                    -DestinationPath dist\bundle.zip

      # ---------------- SHA256 ----------------
      - name: SHA256 checksums
        run: |
          $files = Get-ChildItem dist -File -Exclude SHA256SUMS.txt
          if ($files.Count -gt 0) {
            $files | ForEach-Object {
                $h = Get-FileHash $_.FullName -Algorithm SHA256
                "$($h.Hash)  $($_.Name)"
            } | Out-File dist\SHA256SUMS.txt -Encoding ascii
          } else {
            Write-Host "⚠️ No files to hash, skipping SHA256SUMS.txt"
          }

      # ---------------- Release ----------------
      - name: Prepare release notes
        run: |
          @"
          Bundle build for Windows x64 + i686

          - Arti version: $env:arti_version
          - Lyrebird, Snowflake, WebTunnel: latest main snapshot
          "@ | Out-File RELEASE_NOTES.md -Encoding utf8

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.arti_version }}
          name: "Tor bundle (${{ env.arti_version }})"
          body_path: RELEASE_NOTES.md
          files: |
            dist/arti-x64.zip
            dist/arti-i686.zip
            dist/lyrebird-x64.zip
            dist/lyrebird-i686.zip
            dist/snowflake-x64.zip
            dist/snowflake-i686.zip
            dist/webtunnel-x64.zip
            dist/webtunnel-i686.zip
            dist/bundle.zip
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
